/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Analysis
         * @description Analyze one image with browser-authored regions without persisting either.
         */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report local service readiness.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Preview
         * @description Decode one image and return a compressed, display-only preview.
         */
        post: operations["createPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Analysis
         * @description Analysis result paired with the validated regions that produced it.
         */
        Analysis: {
            regions: components["schemas"]["Regions"];
            result: components["schemas"]["Result"];
        };
        /** Body_createAnalysis */
        Body_createAnalysis: {
            /**
             * Image
             * @description RAW or raster image
             */
            image: string;
            /**
             * Regions
             * @description Normalized region JSON
             */
            regions: string;
        };
        /** Body_createPreview */
        Body_createPreview: {
            /**
             * Image
             * @description RAW or raster image
             */
            image: string;
        };
        /**
         * CaptureMetadata
         * @description Normalized photographic context used to compare scene captures.
         */
        CaptureMetadata: {
            /** Aperture F Number */
            aperture_f_number?: number | null;
            /** Camera Make */
            camera_make?: string | null;
            /** Camera Model */
            camera_model?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /** Color Space */
            color_space?: string | null;
            /** Exposure Compensation Ev */
            exposure_compensation_ev?: number | null;
            /** Exposure Time Seconds */
            exposure_time_seconds?: number | null;
            /** Exposure Value Ev100 */
            exposure_value_ev100?: number | null;
            /** File Format */
            file_format: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Focal Length 35Mm Mm */
            focal_length_35mm_mm?: number | null;
            /** Focal Length Mm */
            focal_length_mm?: number | null;
            /** Height Px */
            height_px: number;
            /** Iso */
            iso?: number | null;
            /** Lens */
            lens?: string | null;
            /** Metering Mode */
            metering_mode?: string | null;
            /** Orientation */
            orientation?: string | null;
            /** White Balance */
            white_balance?: string | null;
            /** Width Px */
            width_px: number;
        };
        /**
         * FocusTile
         * @description One normalized target tile in the local sharpness map.
         */
        FocusTile: {
            /** Height */
            height: number;
            /** In Focus */
            in_focus: boolean;
            /** Relative Sharpness */
            relative_sharpness: number;
            /** Sharpness */
            sharpness: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Health
         * @description Service readiness response.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * ImageMetadata
         * @description Normalized comparison fields plus namespaced source metadata.
         */
        ImageMetadata: {
            /** Entries */
            entries: components["schemas"]["MetadataEntry"][];
            /**
             * Entries Truncated
             * @default false
             */
            entries_truncated: boolean;
            summary: components["schemas"]["CaptureMetadata"];
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
        };
        /**
         * MetadataEntry
         * @description One bounded, display-safe metadata entry from the source image.
         */
        MetadataEntry: {
            group: components["schemas"]["MetadataGroup"];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Sensitive
             * @default false
             */
            sensitive: boolean;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Value */
            value: string;
        };
        /** @enum {string} */
        MetadataGroup: "file" | "image" | "exif" | "gps" | "camera" | "thumbnail" | "xmp" | "other";
        /**
         * Metrics
         * @description Primary transparent scene-visibility KPIs.
         */
        Metrics: {
            /** Bright Blue Clipped 99 Percent */
            bright_blue_clipped_99_percent: number;
            /** Bright Clipped 99 9 Percent */
            bright_clipped_99_9_percent: number;
            /** Bright Clipped 99 Percent */
            bright_clipped_99_percent: number;
            /** Bright Green Clipped 99 Percent */
            bright_green_clipped_99_percent: number;
            /** Bright Red Clipped 99 Percent */
            bright_red_clipped_99_percent: number;
            /** Cnr Robust */
            cnr_robust: number;
            /** Cnr Standard */
            cnr_standard: number;
            /** Dr Local Median Stops */
            dr_local_median_stops: number;
            /** Dr Target Median Stops */
            dr_target_median_stops: number;
            /** Dr Target P95 To P50 Stops */
            dr_target_p95_to_p50_stops: number;
            /** Dr Target P99 To P50 Stops */
            dr_target_p99_to_p50_stops: number;
            /** Image Clipped 99 Percent */
            image_clipped_99_percent: number;
            /** Michelson Contrast */
            michelson_contrast: number;
            /** Snr Target Robust */
            snr_target_robust: number;
            /** Snr Target Standard */
            snr_target_standard: number;
            /** Target Below 0 1 Percent */
            target_below_0_1_percent: number;
            /** Target Below 0 25 Percent */
            target_below_0_25_percent: number;
            /** Target Below 0 5 Percent */
            target_below_0_5_percent: number;
            /** Target Below 1 Percent */
            target_below_1_percent: number;
            /** Target Below 2 Percent */
            target_below_2_percent: number;
            /** Target Below Shadow Threshold */
            target_below_shadow_threshold: number;
            /** Target Clipped 99 Percent */
            target_clipped_99_percent: number;
            /** Weber Contrast Absolute */
            weber_contrast_absolute: number;
            /** Weber Contrast Signed */
            weber_contrast_signed: number;
        };
        Point: [
            number,
            number
        ];
        /**
         * Polygon
         * @description A normalized polygonal region.
         */
        Polygon: {
            /** Points */
            points: components["schemas"]["Point"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "polygon";
        };
        /**
         * Preview
         * @description Compressed display preview and source information.
         */
        Preview: {
            bright_background_suggestion: components["schemas"]["Rectangle"];
            /** Height Px */
            height_px: number;
            /** Image */
            image: string;
            metadata: components["schemas"]["ImageMetadata"];
            /** Preview Data Url */
            preview_data_url: string;
            processing: components["schemas"]["Processing"];
            /**
             * Version
             * @default 2
             * @constant
             */
            version: 2;
            /** Width Px */
            width_px: number;
        };
        /**
         * Problem
         * @description Stable caller-facing error envelope.
         */
        Problem: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Processing
         * @description Reproducible processing choices applied before measurement.
         */
        Processing: {
            /** Black Level Per Channel */
            black_level_per_channel?: number[] | null;
            /** Linear */
            linear: boolean;
            /** Profile */
            profile: string;
            /** Settings */
            settings: {
                [key: string]: components["schemas"]["SettingValue"];
            };
            /**
             * Source
             * @enum {string}
             */
            source: "raw" | "raster";
            /** White Balance Policy */
            white_balance_policy: string;
            /** White Level */
            white_level?: number | null;
        };
        /**
         * QualityAnalysis
         * @description Quality KPIs and bounded diagnostics calculated at a reproducible scale.
         */
        QualityAnalysis: {
            /** Analysis Height Px */
            analysis_height_px: number;
            /** Analysis Width Px */
            analysis_width_px: number;
            /** Focus Map */
            focus_map: components["schemas"]["FocusTile"][];
            /** Focus Relative Threshold */
            focus_relative_threshold: number;
            metrics: components["schemas"]["QualityMetrics"];
            /** Warnings */
            warnings: string[];
        };
        /**
         * QualityMetrics
         * @description Transparent capture-quality measurements derived from linear source samples.
         */
        QualityMetrics: {
            /** Banding Fraction */
            banding_fraction: number | null;
            /** Center To Corner Falloff */
            center_to_corner_falloff: number | null;
            /** Channel Saturation Clipping */
            channel_saturation_clipping: number;
            /** Chroma Noise */
            chroma_noise: number | null;
            /** Detail To Noise Ratio */
            detail_to_noise_ratio: number | null;
            /** Directional Blur Angle Degrees */
            directional_blur_angle_degrees: number | null;
            /** Directional Blur Anisotropy */
            directional_blur_anisotropy: number | null;
            /** Jpeg Blockiness */
            jpeg_blockiness: number | null;
            /** Luminance Noise */
            luminance_noise: number | null;
            /** Ringing Halo Strength */
            ringing_halo_strength: number | null;
            /** Target Edge Acutance */
            target_edge_acutance: number | null;
            /** Target Edge Width Px */
            target_edge_width_px: number | null;
            /** Target In Focus Coverage */
            target_in_focus_coverage: number | null;
            /** Target Sharpness */
            target_sharpness: number;
            /** Target Sharpness Consistency */
            target_sharpness_consistency: number | null;
        };
        /**
         * Rectangle
         * @description A normalized rectangular region.
         */
        Rectangle: {
            /** Height */
            height: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rectangle";
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        Region: components["schemas"]["Rectangle"] | components["schemas"]["Polygon"];
        /**
         * RegionStatistics
         * @description Robust and conventional statistics for one region.
         */
        RegionStatistics: {
            /** Coefficient Of Variation */
            coefficient_of_variation: number | null;
            /** Interquartile Range */
            interquartile_range: number;
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Minimum */
            minimum: number;
            /** Percentile 1 */
            percentile_1: number;
            /** Percentile 25 */
            percentile_25: number;
            /** Percentile 5 */
            percentile_5: number;
            /** Percentile 5 To 95 Range */
            percentile_5_to_95_range: number;
            /** Percentile 75 */
            percentile_75: number;
            /** Percentile 95 */
            percentile_95: number;
            /** Percentile 99 */
            percentile_99: number;
            /** Pixel Count */
            pixel_count: number;
            /** Robust Sigma */
            robust_sigma: number;
            /** Standard Deviation */
            standard_deviation: number;
        };
        /**
         * Regions
         * @description The three regions required for primary visibility analysis.
         */
        Regions: {
            bright_background: components["schemas"]["Region"];
            local_background: components["schemas"]["Region"];
            target: components["schemas"]["Region"];
        };
        /**
         * Result
         * @description Versioned, serializable result for one analyzed scene.
         */
        Result: {
            /** Image */
            image: string;
            metadata: components["schemas"]["ImageMetadata"];
            metrics: components["schemas"]["Metrics"];
            /**
             * Preview Notice
             * @default Preview brightness has been adjusted. Metrics were calculated from linear source data.
             */
            preview_notice: string;
            processing: components["schemas"]["Processing"];
            quality: components["schemas"]["QualityAnalysis"];
            /** Region Statistics */
            region_statistics: {
                [key: string]: components["schemas"]["RegionStatistics"];
            };
            /** Scene Id */
            scene_id: string;
            /**
             * Version
             * @default 3
             */
            version: number;
            /** Warnings */
            warnings: string[];
        };
        SettingValue: string | number | boolean | number[] | number[] | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createAnalysis"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createPreview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
